[package]
name = "code_diary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
chrono = "0.4.26"
color-print = "0.3.4"
regex = "1.9.1"
requestty = "0.5.0"
sqlite = "0.31.0"
